### ISSUE TITLE
Output data units differ from the new four-span format

### ISSUE THREAD

**Issue by Ruyi-Feng** [open-v2x/cerebrum#17]
## Describe the bug

Output data units differ from the new four-span format.

## To Reproduce
N/A

## Expected behavior
N/A

## Screenshots

N/A

## Log Information

N/A

## Desktop (please complete the following information):

- OS: MACOS
- Browser: N/A
- Version: master

## Additional context
N/A

**Comment by ghost** [comment]
「吴文相：@冯汝怡Ruyi 航向角 / 速度 意义，应该没有负数，就是 fix 这个对吧？」
- - - - - - - - - - - - - - -
对的。把输出单位统一，之前出问题的地方改掉了。
