### ISSUE TITLE
Performance test, RSM trajectory data packet loss issue

### ISSUE THREAD

**Issue by li-qi-cool** [open-v2x/cerebrum#30]
## Describe the bug

Performance test, when sending RSM trajectory data, send 4-25 vehicle data according to a frame of 100ms, the actual received data has packet loss problem

## To Reproduce

1. Using the performance test framework, send rsm data, the sending frequency is 0.1s
2. Send 1000 frames of data, check the sending result

## Expected behavior

Received 1000 frames of data, the packet loss rate is 0

## Active behavior

The received data is less than 1000 frames, and the packet loss rate is 3%

## Screenshots

![截屏2022-07-29 下午11 14 27](https://user-images.githubusercontent.com/100892547/181790488-d8428425-f99a-477f-afa1-8cd5e191d11e.png)

## Log Information

N/A

## Desktop (please complete the following information):

- OS: MACOS
- Tool: python 
- Version/branch: master/abanly
- 
## Additional context

N/A

**Comment by Wd77Baby** [comment]
The reason for the packet loss phenomenon is that the algorithm service ensures that the data frame numbers entering the algorithm are in order, so if the current frame number is smaller than the previous frame, the algorithm service will actively discard the frame data. The current algorithm logic, as long as multiple frames of data are not continuously lost, has no effect on the algorithm's processing and due effects.

**Comment by li-qi-cool** [comment]
Close the issue as described above
