### ISSUE TITLE
[mac] mac 环境如何配置开发呢，有文档么

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [open-v2x/cerebrum#72]

**Comment by ghost** [comment]
emmmmmm，单纯一个 cerebrum 肯定可以在 mac 上跑起来。其它的服务你要一个个搭建：
1. 基础服务：redis / mysql / mqtt server
2. 以及依赖的 dandelion

**Comment by ghost** [comment]
。

**Comment by wangwenqiangGitHub** [comment]
> 。

`https://openv2x.org/posts/2022-08-27-1/`看了咱们这个博客，是服务器上的，什么时候出个mac的环境配置

**Comment by ghost** [comment]
> `https://openv2x.org/posts/2022-08-27-1/`看了咱们这个博客，是服务器上的，什么时候出个mac的环境配置

1. 最简单的，你可以 mac 上开个 2 Core 4 G 的虚拟机……
2. 得自己在 MAC 上跑 redis / mysql / mqtt server / dandelion 四个服务，要初始化

我自己也是用 mac，我就是 VM 方案开发的。用 vscode 远程调试 VM 里的代码

**Comment by wangwenqiangGitHub** [comment]
> > `https://openv2x.org/posts/2022-08-27-1/`看了咱们这个博客，是服务器上的，什么时候出个mac的环境配置
> 
> 1. 最简单的，你可以 mac 上开个 2 Core 4 G 的虚拟机……
> 2. 得自己在 MAC 上跑 redis / mysql / mqtt server / dandelion 四个服务，要初始化
> 
> 我自己也是用 mac，我就是 VM 方案开发的。用 vscode 远程调试 VM 里的代码

好的，我试试

**Comment by wangwenqiangGitHub** [comment]
> 2\. MAC 上跑 redis / mysql / mqtt server / dandelion 四个服务

MAC 上跑 redis / mysql / mqtt server / dandelion 四个服务, 不是在虚拟机上跑

**Comment by ghost** [comment]
嗯，主要是现在 docker-desktop 对中等规模企业要收费的。
如果 mac 上跑 docker 容器，得付钱，所以不如直接用 VM 跑容器
